### ISSUE TITLE
Error when .trunk/logs (config.out_file) doesn't exist

### ISSUE THREAD

**Issue by docwhat** [trunk-io/neovim-trunk#16]
If the `config.out_file`'s directory doesn't exist, then the plugin throws an error when trying to write the log file.

### The code

The code is [lua/log.lua:151](https://github.com/trunk-io/neovim-trunk/blob/1a14c42f1c25b7a7a861febb6c8d598b6d9d509e/lua/log.lua#L151)

```lua
-- Output to log file
if config.use_file then
	local fp = io.open(config.out_file, "a")
	local str = string.format("[%-6s%s] %s: %s\n", nameupper, os.date(), lineinfo, msg)
	fp:write(str) -- <-- error thrown here
	fp:close()
end
```

### The error message

```
Failed to run `config` for lsp-zero.nvim

.../.local/share/nvim/lazy/neovim-trunk/lua/log.lua:151: attempt to index local 'fp' (a nil value)

# stacktrace:
  - /neovim-trunk/lua/log.lua:151 _in_ **info**
  - /neovim-trunk/lua/trunk.lua:28
  - ...
```

### The workarounds

- set `config.use_file = false`
- set `config.out_file` to some place that exists.

**Comment by TylerJang27** [comment]
Thanks for reporting this! It should be fixed in the latest release `v0.1.3`. Please let us know if you encounter any other issues
